---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5

    - name: Check Interface status
      junos_command:
        commands:
          - show interfaces terse | json
        wait_for:
          - result[0] contains up 
      register: junos

    - name: Print version
      debug:
        var: junos.stdout_lines
        #var: result

#    - name: collect default set of facts
#      junos_facts:
#        gather_subset: config
