---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
        - name: Checking NETCONF connectivity
          wait_for: 
           host: "{{ inventory_hostname }}"
           port: 22 
          vars:
           ansible_command_timeout: 300


        - name: Enable netconf service on port 22
          junos_netconf:
            listens_on: 22
            state: present

#        - name: disable netconf service
#          junos_netconf:
#            state: absent

#        - name: enable netconf service on port 22
#          junos_netconf:
#            listens_on: 22
#            state: present
