---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5
      register: junos

    - name: Print output
      debug:
        var: junos

    - name: Load Interface IP Config
      junos_l3_interface:
        name: ge-0/0/0
        unit: 0
        ipv4: 10.0.1.1/24
      register: junos1

    - name: Print output
      debug:
        var: junos1

    - name: Load interface Desciption Config
      junos_interface:
        name: ge-0/0/0
        description: "test-interface|new" 
        #state: absent
      register: junos2

    - name: Print output
      debug:
        var: junos2

#    - name: Print
#      debug:
#        var: junos

