---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5

    - name: run show version and check to see if output contains 15.1X49
      junos_command:
        commands: show version
        wait_for: result[0] contains 15.1X49
      register: junos

    - name: Print version
      debug:
        var: junos

#    - name: collect default set of facts
#      junos_facts:
#        gather_subset: config
