---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5

    - name: Configure VLAN ID and name
      junos_vlan:
        #vlan_name: test
        vlan_id: 20
        name: test-vlan
        description: test-vlan
        state: present
        active: True
      register: junos

    - name: Configure VLAN ID and name
      junos_vlan:
        #vlan_name: test
        vlan_id: 20
        name: test-vlan
        interfaces: ge-0/0/0
        l3_interface: irb.20
        description: test-vlan
      #  state: present
      #  active: False
      register: junos
        
    - name: Print
      debug:
        var: junos
