---
- name: Get Device Facts
  hosts: alljunos
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5

#    - name: Retrieving information from devices running Junos OS
#      juniper_junos_facts:
#        host: "{{ inventory_hostname }}"
#
#    - name: Print version
#      debug:
#        var: junos.version

#    - name: run show version on remote devices
#      junos_command:
#        commands: show version
#        wait_for: result[0] contains 17.4R

#    - name: Run rpc on the remote device
#      junos_command:
#        commands: show configuration
#        display: set
#      register: junos

#    - name: Print results
#      debug:
#        var: junos.stdout_lines


    - name: Run rpc on the remote device
      junos_command:
        commands: show configuration
        display: set
      register: junos

    - name: Print results
      debug:
        msg: '{{junos.stdout_lines}}'
