---
- name: Get Device Facts
  hosts: srx
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 5
