---
- name: Get Device Facts
  hosts: r1.netauto
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no

  tasks:
   - name: Checking NETCONF connectivity
     wait_for: 
      host: "{{ inventory_hostname }}"
      port: 22
     vars:
      ansible_command_timeout: 300

   - name: Configure interface in access mode
     junos_l2_interface:
       name: ge-0/0/0
       description: interface-access
       mode: access
       timeout: 300
       access_vlan: mgmt
       active: True
       state: present

#        - name: disable netconf service
#          junos_netconf:
#            state: absent

#        - name: enable netconf service on port 22
#          junos_netconf:
#            listens_on: 22
#            state: present
