---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:

    - name: load configure lines into device
      junos_config:
        lines:
          - delete interfaces ge-0/0/1 unit 0 description "Test interface"
          - delete vlans vlan01 description "Test vlan"
        comment: update config
      vars:
        ansible_command_timeout: 300

    - name: confirm a previous commit
      junos_config:
        confirm_commit: yes
      vars:
        ansible_command_timeout: 300

