---
- name: Get Device Facts
  hosts: r1
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
        timeout: 20

    - name: rollback the configuration
      junos_rollback:
        rollback=2
        confirm=5
      vars:
        ansible_command_timeout: 300

