---
- name: Get Device Facts
  hosts: r1.netauto
  roles:
    - Juniper.junos 
  connection: netconf
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}"
        port: 22 
      vars:
        ansible_command_timeout: 300

    - name: confirm a previous commit
      junos_config:
        confirm_commit: yes
      vars:
        ansible_command_timeout: 300

    - name: rollback the configuration
      junos_rollback:
        rollback=1
      vars:
        ansible_command_timeout: 300
